[Definition]
failregex = ^.*SecurityEvent="(FailedACL|InvalidAccountID|ChallengeResponseFailed|InvalidPassword|AuthMethodNotAllowed|RequestNotAllowed)".*RemoteAddress="IPV[46]/(UDP|TCP|TLS)/<HOST>/[0-9]+".*$
            ^.*Request '(INVITE|REGISTER|OPTIONS)' from '.*' failed for '<HOST>:[0-9]+' \(callid: .*\) - No matching endpoint found.*$
            ^.*Request '(INVITE|REGISTER|OPTIONS)' from '.*' failed for '<HOST>:[0-9]+' \(callid: .*\) - Failed to authenticate.*$
ignoreregex =
