/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      // "The Precision Curator" 디자인 시스템 팔레트
      colors: {
        'tertiary-fixed': '#89f5e7',
        'surface-container-low': '#f3f4f5',
        'on-surface-variant': '#434654',
        'surface-dim': '#d9dadb',
        'on-secondary': '#ffffff',
        'secondary-container': '#d6e0f1',
        'on-tertiary-container': '#84f0e2',
        'secondary-fixed': '#d9e3f4',
        'error': '#ba1a1a',
        'surface-tint': '#1353d8',
        'inverse-surface': '#2e3132',
        'surface-variant': '#e1e3e4',
        'primary-fixed-dim': '#b5c4ff',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e7e8e9',
        'on-error-container': '#93000a',
        'surface-container': '#edeeef',
        'surface-bright': '#f8f9fa',
        'on-primary-fixed': '#00174d',
        'primary-fixed': '#dbe1ff',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#005049',
        'background': '#f8f9fa',
        'tertiary': '#00544c',
        'surface-container-lowest': '#ffffff',
        'primary': '#003fb1',
        'outline-variant': '#c3c5d7',
        'on-primary-fixed-variant': '#003dab',
        'secondary-fixed-dim': '#bdc7d8',
        'on-secondary-fixed': '#121c28',
        'error-container': '#ffdad6',
        'on-primary-container': '#d4dcff',
        'on-background': '#191c1d',
        'inverse-primary': '#b5c4ff',
        'primary-container': '#1a56db',
        'tertiary-container': '#006e65',
        'tertiary-fixed-dim': '#6bd8cb',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'surface': '#f8f9fa',
        'inverse-on-surface': '#f0f1f2',
        'outline': '#737686',
        'secondary': '#555f6d',
        'on-secondary-fixed-variant': '#3e4755',
        'on-tertiary-fixed': '#00201d',
        'on-secondary-container': '#596372',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'Pretendard', 'Noto Sans KR', 'system-ui', 'sans-serif'],
        label: ['Inter', 'Pretendard', 'Noto Sans KR', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        // "Soft-Focus" ambient shadow — 프로 느낌의 확산광
        panel: '0 20px 40px rgba(25, 28, 29, 0.06)',
        // 플로팅 요소용 약간 더 진한 버전
        float: '0 24px 48px rgba(25, 28, 29, 0.12)',
      },
      backgroundImage: {
        // CTA 그라디언트 — primary → primary-container 135deg
        'primary-gradient': 'linear-gradient(135deg, #003fb1 0%, #1a56db 100%)',
      },
    },
  },
  plugins: [],
};
