/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      // v2 Operator — tokens bridged to CSS variables
      colors: {
        'bg-0': 'var(--bg-0)',
        'bg-1': 'var(--bg-1)',
        'bg-2': 'var(--bg-2)',
        'bg-3': 'var(--bg-3)',
        'bg-4': 'var(--bg-4)',
        'fg-1': 'var(--fg-1)',
        'fg-2': 'var(--fg-2)',
        'fg-3': 'var(--fg-3)',
        'fg-4': 'var(--fg-4)',
        'line-1': 'var(--line-1)',
        'line-2': 'var(--line-2)',
        'line-3': 'var(--line-3)',
        signal: 'var(--signal)',
        'signal-soft': 'var(--signal-soft)',
        'signal-dim': 'var(--signal-dim)',
        'on-signal': 'var(--on-signal)',
        'accent-info': 'var(--accent-info)',
        'accent-warn': 'var(--accent-warn)',
        'accent-danger': 'var(--accent-danger)',
        'accent-info-soft': 'var(--accent-info-soft)',
        'accent-warn-soft': 'var(--accent-warn-soft)',
        'accent-danger-soft': 'var(--accent-danger-soft)',
        'status-available': 'var(--status-available)',
        'status-ringing': 'var(--status-ringing)',
        'status-talking': 'var(--status-talking)',
        'status-acw': 'var(--status-acw)',
        'status-break': 'var(--status-break)',
        'status-training': 'var(--status-training)',
        'status-offline': 'var(--status-offline)',

        // Legacy aliases — keep old class names compiling without restyling every file
        primary: 'var(--signal)',
        'on-primary': 'var(--on-signal)',
        'primary-container': 'var(--signal-dim)',
        'on-primary-container': 'var(--fg-1)',
        secondary: 'var(--fg-2)',
        'on-secondary': 'var(--bg-0)',
        'secondary-container': 'var(--bg-2)',
        'on-secondary-container': 'var(--fg-1)',
        tertiary: 'var(--accent-info)',
        'on-tertiary': 'var(--bg-0)',
        'tertiary-container': 'var(--accent-info-soft)',
        'on-tertiary-container': 'var(--accent-info)',
        error: 'var(--accent-danger)',
        'on-error': 'var(--bg-0)',
        'error-container': 'var(--accent-danger-soft)',
        'on-error-container': 'var(--accent-danger)',
        background: 'var(--bg-0)',
        'on-background': 'var(--fg-1)',
        surface: 'var(--bg-1)',
        'surface-bright': 'var(--bg-2)',
        'surface-dim': 'var(--bg-0)',
        'surface-variant': 'var(--bg-2)',
        'surface-tint': 'var(--signal)',
        'surface-container-lowest': 'var(--bg-0)',
        'surface-container-low': 'var(--bg-1)',
        'surface-container': 'var(--bg-1)',
        'surface-container-high': 'var(--bg-2)',
        'surface-container-highest': 'var(--bg-3)',
        'inverse-surface': 'var(--fg-1)',
        'inverse-on-surface': 'var(--bg-0)',
        'inverse-primary': 'var(--signal)',
        'on-surface': 'var(--fg-1)',
        'on-surface-variant': 'var(--fg-2)',
        outline: 'var(--line-3)',
        'outline-variant': 'var(--line-2)',
        'tertiary-fixed': 'var(--accent-info)',
        'tertiary-fixed-dim': 'var(--accent-info)',
        'primary-fixed': 'var(--signal-soft)',
        'primary-fixed-dim': 'var(--signal-dim)',
        'secondary-fixed': 'var(--bg-2)',
        'secondary-fixed-dim': 'var(--bg-3)',
        'on-primary-fixed': 'var(--on-signal)',
        'on-primary-fixed-variant': 'var(--signal)',
        'on-secondary-fixed': 'var(--fg-1)',
        'on-secondary-fixed-variant': 'var(--fg-2)',
        'on-tertiary-fixed': 'var(--fg-1)',
        'on-tertiary-fixed-variant': 'var(--accent-info)',
      },
      borderRadius: {
        DEFAULT: '4px',
        sm: '4px',
        md: '8px',
        lg: '8px',
        xl: '8px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Pretendard Variable', 'Pretendard', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'sans-serif'],
        body: ['Pretendard Variable', 'Pretendard', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'sans-serif'],
        label: ['Pretendard Variable', 'Pretendard', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SF Mono', 'Menlo', 'monospace'],
      },
      boxShadow: {
        panel: 'none',
        float: '0 8px 24px rgba(0, 0, 0, 0.4), 0 2px 4px rgba(0, 0, 0, 0.2)',
      },
      backgroundImage: {
        'primary-gradient': 'none',
      },
    },
  },
  plugins: [],
};
