import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { ConfigService } from '@nestjs/config';
import { PromptTtsService } from './prompt-tts.service';

describe('PromptTtsService', () => {
  const tenantId = '00000000-0000-0000-0000-000000000001';
  let tmpDir: string;
  let soundsDir: string;
  let prisma: any;
  let service: PromptTtsService;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'kaster-tts-'));
    soundsDir = path.join(tmpDir, 'custom');
    prisma = {
      asteriskPrompt: {
        findFirst: jest.fn().mockResolvedValue(null),
        create: jest.fn().mockResolvedValue({
          id: 'prompt-1',
          tenantId,
          promptKey: 'custom/welcome',
          displayName: '환영 멘트',
          fileName: 'welcome.wav',
          category: 'ivr',
          description: 'TTS generated by local-wav',
          isActive: true,
        }),
      },
      promptGenerationJobs: {
        create: jest.fn().mockResolvedValue({
          promptGenerationJobId: 'job-1',
          promptKey: 'custom/welcome',
          fileName: 'welcome.wav',
        }),
        update: jest.fn().mockImplementation(({ data }: any) => Promise.resolve({ promptGenerationJobId: 'job-1', ...data })),
      },
    };
    const config = {
      get: jest.fn((key: string, fallback?: string) => {
        if (key === 'ASTERISK_SOUNDS_DIR') return soundsDir;
        if (key === 'PROMPT_TTS_PROVIDER') return 'local-wav';
        return fallback;
      }),
    } as unknown as ConfigService;

    service = new PromptTtsService(prisma, config);
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('creates a prompt generation job, writes WAV files, and registers the prompt', async () => {
    const result = await service.createPromptFromText(tenantId, {
      text: '안녕하세요. 고객센터입니다.',
      displayName: '환영 멘트',
      promptKey: 'custom/welcome',
      category: 'ivr',
    });

    expect(result.prompt.id).toBe('prompt-1');
    expect(prisma.promptGenerationJobs.create).toHaveBeenCalledWith(expect.objectContaining({
      data: expect.objectContaining({
        tenantId,
        promptKey: 'custom/welcome',
        status: 'PENDING',
      }),
    }));
    expect(prisma.asteriskPrompt.create).toHaveBeenCalledWith(expect.objectContaining({
      data: expect.objectContaining({
        tenantId,
        promptKey: 'custom/welcome',
        fileName: 'welcome.wav',
      }),
    }));

    const primaryWav = fs.readFileSync(path.join(soundsDir, 'welcome.wav'));
    const languageWav = fs.readFileSync(path.join(tmpDir, 'en', 'custom', 'welcome.wav'));
    expect(primaryWav.toString('ascii', 0, 4)).toBe('RIFF');
    expect(primaryWav.toString('ascii', 8, 12)).toBe('WAVE');
    expect(languageWav.toString('ascii', 0, 4)).toBe('RIFF');
  });

  it('marks the job failed when the provider is not configured', async () => {
    const config = {
      get: jest.fn((key: string, fallback?: string) => {
        if (key === 'ASTERISK_SOUNDS_DIR') return soundsDir;
        if (key === 'PROMPT_TTS_PROVIDER') return 'http-json';
        return fallback;
      }),
    } as unknown as ConfigService;
    service = new PromptTtsService(prisma, config);

    await expect(service.createPromptFromText(tenantId, {
      text: '실패 테스트',
      displayName: '실패 멘트',
      promptKey: 'custom/fail',
    })).rejects.toThrow('PROMPT_TTS_HTTP_URL');

    expect(prisma.promptGenerationJobs.update).toHaveBeenCalledWith(expect.objectContaining({
      data: expect.objectContaining({
        status: 'FAILED',
      }),
    }));
  });
});
