import { BadRequestException, Injectable, InternalServerErrorException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as fs from 'fs';
import * as path from 'path';
import { PrismaService } from '../../common/prisma.service';
import { CreatePromptTtsDto } from './dto/create-prompt-tts.dto';

const WAV_HEADER = Buffer.from('RIFF');

interface PromptIdentity {
  promptKey: string;
  fileName: string;
}

@Injectable()
export class PromptTtsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly config: ConfigService,
  ) {}

  async createPromptFromText(tenantId: string, dto: CreatePromptTtsDto) {
    const text = dto.text.trim();
    if (!text) {
      throw new BadRequestException('생성할 멘트 문구를 입력하세요.');
    }

    const displayName = dto.displayName.trim();
    if (!displayName) {
      throw new BadRequestException('멘트명을 입력하세요.');
    }

    const identity = await this.buildUniquePromptIdentity(tenantId, dto.promptKey, displayName);
    const provider = this.resolveProvider();
    const language = dto.language?.trim() || 'ko-KR';
    const voice = dto.voice?.trim() || null;

    const job = await (this.prisma as any).promptGenerationJobs.create({
      data: {
        tenantId,
        promptKey: identity.promptKey,
        displayName,
        fileName: identity.fileName,
        sourceText: text,
        provider,
        voice,
        language,
        status: 'PENDING',
      },
    });

    try {
      await (this.prisma as any).promptGenerationJobs.update({
        where: { promptGenerationJobId: job.promptGenerationJobId },
        data: { status: 'GENERATING' },
      });

      const wav = await this.generateWav(text, { provider, voice, language });
      this.assertWav(wav);
      this.writePromptWav(identity.fileName, wav);

      const prompt = await this.prisma.asteriskPrompt.create({
        data: {
          tenantId,
          promptKey: identity.promptKey,
          displayName,
          fileName: identity.fileName,
          category: dto.category?.trim() || 'ivr',
          description: dto.description?.trim() || `TTS generated by ${provider}`,
          isActive: dto.isActive ?? true,
        },
      });

      const updatedJob = await (this.prisma as any).promptGenerationJobs.update({
        where: { promptGenerationJobId: job.promptGenerationJobId },
        data: {
          promptId: prompt.id,
          status: 'READY',
          generatedBytes: wav.length,
          completedAt: new Date(),
        },
      });

      return { prompt, job: updatedJob };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      await (this.prisma as any).promptGenerationJobs.update({
        where: { promptGenerationJobId: job.promptGenerationJobId },
        data: {
          status: 'FAILED',
          errorMessage: message,
          completedAt: new Date(),
        },
      });
      throw error;
    }
  }

  private async buildUniquePromptIdentity(
    tenantId: string,
    requestedPromptKey: string | undefined,
    displayName: string,
  ): Promise<PromptIdentity> {
    const requestedBase = requestedPromptKey
      ? requestedPromptKey.replace(/^custom\//, '')
      : displayName;
    const base = this.slugify(requestedBase);
    if (!base) {
      throw new BadRequestException('프롬프트 키로 사용할 영문/숫자 이름을 만들 수 없습니다.');
    }

    for (let index = 0; index < 50; index += 1) {
      const suffix = index === 0 ? '' : `-${index + 1}`;
      const candidateBase = `${base}${suffix}`.slice(0, 112);
      const promptKey = `custom/${candidateBase}`;
      const existing = await this.prisma.asteriskPrompt.findFirst({
        where: { tenantId, promptKey },
        select: { id: true },
      });
      if (!existing) {
        return { promptKey, fileName: `${candidateBase}.wav` };
      }
    }

    throw new BadRequestException('사용 가능한 프롬프트 키를 만들 수 없습니다.');
  }

  private slugify(value: string) {
    return value
      .normalize('NFKD')
      .replace(/^custom\//, '')
      .replace(/[^A-Za-z0-9_-]+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
      .toLowerCase();
  }

  private resolveProvider() {
    return this.config.get<string>('PROMPT_TTS_PROVIDER', 'local-wav').trim() || 'local-wav';
  }

  private async generateWav(
    text: string,
    options: { provider: string; voice: string | null; language: string },
  ) {
    if (options.provider === 'http-json') {
      return this.generateWavWithHttpProvider(text, options);
    }

    return this.generateLocalPreviewWav(text);
  }

  private async generateWavWithHttpProvider(
    text: string,
    options: { voice: string | null; language: string },
  ) {
    const endpoint = this.config.get<string>('PROMPT_TTS_HTTP_URL')?.trim();
    if (!endpoint) {
      throw new InternalServerErrorException('PROMPT_TTS_HTTP_URL is required when PROMPT_TTS_PROVIDER=http-json');
    }

    const token = this.config.get<string>('PROMPT_TTS_HTTP_TOKEN')?.trim();
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
      },
      body: JSON.stringify({
        text,
        voice: options.voice,
        language: options.language,
        format: 'wav',
        sampleRate: 8000,
      }),
    });

    if (!response.ok) {
      throw new InternalServerErrorException(`TTS provider returned ${response.status}`);
    }

    const contentType = response.headers.get('content-type') ?? '';
    if (contentType.includes('application/json')) {
      const payload = await response.json() as { audioContent?: string; audioBase64?: string };
      const base64 = payload.audioContent ?? payload.audioBase64;
      if (!base64) {
        throw new InternalServerErrorException('TTS provider JSON response does not contain audioContent');
      }
      return Buffer.from(base64, 'base64');
    }

    return Buffer.from(await response.arrayBuffer());
  }

  private generateLocalPreviewWav(text: string) {
    const sampleRate = 8000;
    const durationSeconds = Math.max(1, Math.min(4, Math.ceil(text.length / 80)));
    const samples = sampleRate * durationSeconds;
    const data = Buffer.alloc(samples * 2);

    for (let i = 0; i < samples; i += 1) {
      const envelope = i < sampleRate / 12 ? i / (sampleRate / 12) : 1;
      const frequency = i % (sampleRate / 2) < sampleRate / 4 ? 440 : 554;
      const value = Math.trunc(Math.sin((2 * Math.PI * frequency * i) / sampleRate) * 900 * envelope);
      data.writeInt16LE(value, i * 2);
    }

    return this.wrapPcmAsWav(data, sampleRate);
  }

  private wrapPcmAsWav(data: Buffer, sampleRate: number) {
    const header = Buffer.alloc(44);
    header.write('RIFF', 0);
    header.writeUInt32LE(36 + data.length, 4);
    header.write('WAVE', 8);
    header.write('fmt ', 12);
    header.writeUInt32LE(16, 16);
    header.writeUInt16LE(1, 20);
    header.writeUInt16LE(1, 22);
    header.writeUInt32LE(sampleRate, 24);
    header.writeUInt32LE(sampleRate * 2, 28);
    header.writeUInt16LE(2, 32);
    header.writeUInt16LE(16, 34);
    header.write('data', 36);
    header.writeUInt32LE(data.length, 40);
    return Buffer.concat([header, data]);
  }

  private assertWav(buffer: Buffer) {
    if (buffer.length < 44 || !buffer.subarray(0, 4).equals(WAV_HEADER) || buffer.toString('ascii', 8, 12) !== 'WAVE') {
      throw new InternalServerErrorException('TTS provider did not return a valid WAV payload');
    }
  }

  private writePromptWav(fileName: string, buffer: Buffer) {
    const soundsDir = this.resolvePromptSoundsDir();
    for (const targetDir of this.resolvePromptTargetDirs(soundsDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
      fs.writeFileSync(path.join(targetDir, fileName), buffer);
    }
  }

  private resolvePromptSoundsDir() {
    const configured = this.config.get<string>('ASTERISK_SOUNDS_DIR', '/var/lib/asterisk/sounds/custom');
    if (!path.isAbsolute(configured)) {
      throw new InternalServerErrorException(`ASTERISK_SOUNDS_DIR must be an absolute path, got "${configured}"`);
    }
    return configured;
  }

  private resolvePromptTargetDirs(soundsDir: string) {
    const rootSoundsDir = path.dirname(soundsDir);
    const customDirName = path.basename(soundsDir);
    const languageCustomDir = path.join(rootSoundsDir, 'en', customDirName);
    return [...new Set([soundsDir, languageCustomDir])];
  }
}
