FROM node:22-bookworm-slim AS builder

WORKDIR /app

COPY apps/server/package.json apps/server/package-lock.json ./
RUN npm ci

COPY apps/server ./
RUN npx prisma generate && npm run build

FROM node:22-bookworm-slim AS runner

ENV NODE_ENV=production
WORKDIR /app

COPY --from=builder /app/package.json /app/package-lock.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/main.js"]
