global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: cti-server
    metrics_path: /metrics
    static_configs:
      - targets:
          - cti-app-1:3000
          - cti-app-2:3000
          - cti-app-3:3000
