[globals]
COMPANY_MAIN_DID=07012345678
REC_BASE_DIR=/var/spool/asterisk/monitor
DEFAULT_QUEUE=sales

#include extensions_inbound.conf
#include extensions_queue.conf
#include extensions_agent.conf
#include extensions_transfer.conf
