[agent-phone]
exten => _X.,1,NoOp(Agent endpoint context ${EXTEN})
 same => n,Hangup()

[outbound-main]
exten => _0X.,1,NoOp(Outbound ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN}@trunk-provider,60,b(func-set-sipheaders^s^1))
 same => n,Hangup()
