[queue-entry]
exten => s,1,NoOp(Queue Entry / ${QUEUE_NAME} / ${CHANNEL(linkedid)})
 same => n,Set(__REC_FILE=${STRFTIME(${EPOCH},,%Y/%m/%d)}/${CHANNEL(linkedid)}-${UNIQUEID}.wav)
 same => n,Set(__CALL_START_TS=${STRFTIME(${EPOCH},,%Y-%m-%d %H:%M:%S)})
 same => n,MixMonitor(${REC_BASE_DIR}/${REC_FILE},b)
 same => n,Set(CDR(userfield)=linkedid=${CHANNEL(linkedid)};queue=${QUEUE_NAME};rec=${REC_FILE})
 same => n,Queue(${QUEUE_NAME},tT,,,45)
 same => n,NoOp(Queue Result: ${QUEUESTATUS})
 same => n,Goto(queue-exit,s,1)

[queue-exit]
exten => s,1,NoOp(Queue Exit / STATUS=${QUEUESTATUS} / ABANDONED?=${ABANDONED})
 same => n,ExecIf($["${QUEUESTATUS}"="TIMEOUT"]?Playback(custom/queue_timeout))
 same => n,Hangup()

[from-queue]
exten => _X.,1,NoOp(From Queue to Agent ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},20,tT)
 same => n,Hangup()
