[agent-phone]
exten => _00.,1,NoOp(Blocked international phone direct outbound ${EXTEN})
 same => n,Playback(ss-noservice)
 same => n,Hangup()

exten => _060XXXXXXX,1,NoOp(Blocked paid phone direct outbound ${EXTEN})
 same => n,Playback(ss-noservice)
 same => n,Hangup()

exten => _060XXXXXXXX,1,NoOp(Blocked paid phone direct outbound ${EXTEN})
 same => n,Playback(ss-noservice)
 same => n,Hangup()

exten => _X.,1,NoOp(Agent endpoint context ${EXTEN})
 same => n,GotoIf($["${PJSIP_DIAL_CONTACTS(${CALLERID(num)})}"=""]?unregistered-agent,1)
 same => n,Hangup()

exten => unregistered-agent,1,NoOp(Registered contact not found for agent caller ${CALLERID(num)})
 same => n,Playback(ss-noservice)
 same => n,Hangup()

[outbound-main]
exten => _00.,1,NoOp(Blocked international outbound ${EXTEN})
 same => n,Playback(ss-noservice)
 same => n,Hangup()

exten => _060XXXXXXX,1,NoOp(Blocked paid outbound ${EXTEN})
 same => n,Playback(ss-noservice)
 same => n,Hangup()

exten => _060XXXXXXXX,1,NoOp(Blocked paid outbound ${EXTEN})
 same => n,Playback(ss-noservice)
 same => n,Hangup()

exten => _0X.,1,NoOp(Outbound ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN}@trunk-provider,60,b(func-set-sipheaders^s^1))
 same => n,Hangup()
