[general]
enabled = yes
webenabled = no
port = 5038
bindaddr = 0.0.0.0

[cti_middleware]
secret = STRONG_AMI_PASSWORD
deny = 0.0.0.0/0.0.0.0
permit = 10.0.0.0/255.0.0.0
permit = 127.0.0.1/255.255.255.255
read = system,call,agent,user,dtmf,log,verbose,command,reporting,cdr,dialplan
write = system,call,agent,user,command,originate,message
writetimeout = 5000
