[global]
type=global
user_agent=KAster_CTI

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[trunk-provider-auth]
type=auth
auth_type=userpass
username=TRUNK_ID
password=TRUNK_PASSWORD

[trunk-provider-aor]
type=aor
contact=sip:TRUNK_IP_OR_DOMAIN:5060

[trunk-provider-identify]
type=identify
endpoint=trunk-provider
match=TRUNK_IP

[trunk-provider]
type=endpoint
transport=transport-udp
context=inbound-main
disallow=all
allow=alaw,ulaw
aors=trunk-provider-aor
outbound_auth=trunk-provider-auth
from_user=TRUNK_ID
from_domain=TRUNK_IP_OR_DOMAIN
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
trust_id_inbound=yes
send_pai=yes

[1001-auth]
type=auth
auth_type=userpass
username=1001
password=1001_SECRET

[1001-aor]
type=aor
max_contacts=1

[1001]
type=endpoint
context=agent-phone
disallow=all
allow=alaw,ulaw
auth=1001-auth
aors=1001-aor
callerid=Agent1001 <1001>
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
