[general]
persistentmembers=yes
autofill=yes
shared_lastcall=yes
keep_stats=yes

[sales]
musicclass=default
strategy=leastrecent
timeout=15
retry=3
wrapuptime=30
maxlen=0
autopause=yes
setinterfacevar=yes
setqueuevar=yes
setqueueentryvar=yes
ringinuse=no
member => Local/1001@from-queue/n,0,Agent1001
member => Local/1002@from-queue/n,0,Agent1002
