export interface MusiconholdClassInput {
  className: string;
  directory: string;
}

export function renderMusiconholdConf(classes: MusiconholdClassInput[]): string {
  const lines: string[] = [
    '; Auto-generated by KAster CTI - do not edit manually',
    '[default]',
    'mode=files',
    'directory=/var/lib/asterisk/moh',
    'random=no',
    '',
  ];

  for (const item of classes) {
    lines.push(`[${item.className}]`);
    lines.push('mode=files');
    lines.push(`directory=${item.directory}`);
    lines.push('random=no');
    lines.push('sort=alpha');
    lines.push('');
  }

  return lines.join('\n');
}
