export interface QueueMemberInput {
  extension: string;
  agentName: string;
  penalty: number;
  memberOrder: number;
}

export interface QueueInput {
  queueName: string;
  strategy: string;
  ringTimeoutSeconds: number;
  retrySeconds: number;
  wrapupSeconds: number;
  maxWaitSeconds: number;
  autopause: boolean;
  members: QueueMemberInput[];
}

export function renderQueuesConf(queues: QueueInput[]): string {
  const lines: string[] = [
    '; Auto-generated by KAster CTI - do not edit manually',
    '[general]',
    'persistentmembers=yes',
    'autofill=yes',
    'ringinuse=no',
    '',
  ];

  for (const q of queues) {
    lines.push(`[${q.queueName}]`);
    lines.push(`strategy=${q.strategy}`);
    lines.push(`timeout=${q.ringTimeoutSeconds}`);
    lines.push(`retry=${q.retrySeconds}`);
    lines.push(`wrapuptime=${q.wrapupSeconds}`);
    lines.push('maxlen=0');
    lines.push(`autopause=${q.autopause ? 'yes' : 'no'}`);

    const sorted = [...q.members].sort(
      (a, b) => a.memberOrder - b.memberOrder || a.penalty - b.penalty,
    );

    for (const m of sorted) {
      lines.push(`member => PJSIP/${m.extension},${m.penalty},${m.agentName}`);
    }

    lines.push('');
  }

  return lines.join('\n');
}
